services:
  lixozero-db:
    container_name: lixozero-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=lixo-zero
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=lixo-zero
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data:rw
    networks:
      - lixozero-network
  
  lixozero-api:
    container_name: lixozero-api
    build:
      context: .
    restart: always
    depends_on:
      - lixozero-db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
    networks:
      - proxy-manager
      - lixozero-network
    expose:
      - 3000

networks:
  lixozero-network:
    name: lixozero-network
    
  proxy-manager:
    name: proxy-manager
    external: true
