services:
  db:
    container_name: lixo_zero_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=lixo_zero
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=lixo_zero
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data:rw
    networks:
      - lixo_zero_network
  
  api:
    container_name: lixo_zero_api
    build:
      context: .
    restart: always
    depends_on:
      - db
    networks:
      - lixo_zero_network
    ports:
      - 3000:3000

networks:
  lixo_zero_network:
