services:
  lixozero_db:
    container_name: lixozero_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=lixo_zero
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=lixo_zero
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data:rw
    networks:
      - lixozero_network
  
  lixozero_api:
    container_name: lixozero_api
    build:
      context: .
    restart: always
    depends_on:
      - lixozero_db
    networks:
      - proxy_manager
      - lixozero_network
    expose:
      - 3000

networks:
  lixozero_network:
    name: lixozero_network

  proxy_manager:
    name: proxy_manager
